# Generated by Django 3.1.4 on 2020-12-15 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proximity_to_volcano', models.FloatField()),
                ('is_underwater_coverage', models.BooleanField()),
                ('is_super_volcano_coverage', models.BooleanField()),
                ('coverage_limit', models.FloatField()),
                ('premium', models.FloatField()),
                ('tax', models.FloatField()),
                ('convienience_fee', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('effective_date', models.DateField()),
                ('had_previous_policy_cancelled', models.BooleanField(default=False)),
                ('distance_to_volcano', models.FloatField()),
                ('is_owned', models.BooleanField()),
                ('mailing_address', models.TextField()),
                ('property_address', models.TextField()),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.plan')),
            ],
        ),
    ]
