# Generated by Django 3.1.4 on 2020-12-17 01:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line1', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('zip_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PlanVariable',
            fields=[
                ('variable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.variable')),
            ],
            bases=('api.variable',),
        ),
        migrations.CreateModel(
            name='RateVariable',
            fields=[
                ('variable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.variable')),
                ('plans', models.ManyToManyField(related_name='rate_variables', to='api.Plan')),
            ],
            bases=('api.variable',),
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quote_number', models.CharField(max_length=10)),
                ('effective_date', models.DateField()),
                ('previous_policy_cancelled', models.BooleanField(default=False)),
                ('property_mileage_to_nearest_volcano', models.FloatField()),
                ('owns_property_to_be_insured', models.BooleanField()),
                ('mailing_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailing_address', to='api.address')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='api.plan')),
                ('property_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_address', to='api.address')),
            ],
        ),
        migrations.CreateModel(
            name='BoolPlanVariable',
            fields=[
                ('planvariable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.planvariable')),
                ('value', models.BooleanField()),
            ],
            bases=('api.planvariable',),
        ),
        migrations.CreateModel(
            name='BoolRateVariable',
            fields=[
                ('ratevariable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.ratevariable')),
                ('value', models.BooleanField()),
            ],
            bases=('api.ratevariable',),
        ),
        migrations.CreateModel(
            name='FltPlanVariable',
            fields=[
                ('planvariable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.planvariable')),
                ('value', models.FloatField()),
            ],
            bases=('api.planvariable',),
        ),
        migrations.CreateModel(
            name='FltRateVariable',
            fields=[
                ('ratevariable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.ratevariable')),
                ('value', models.FloatField()),
            ],
            bases=('api.ratevariable',),
        ),
        migrations.CreateModel(
            name='IntPlanVariable',
            fields=[
                ('planvariable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.planvariable')),
                ('value', models.IntegerField()),
            ],
            bases=('api.planvariable',),
        ),
        migrations.CreateModel(
            name='IntRateVariable',
            fields=[
                ('ratevariable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.ratevariable')),
                ('value', models.IntegerField()),
            ],
            bases=('api.ratevariable',),
        ),
        migrations.CreateModel(
            name='ProximityToVolcanoPlanVariable',
            fields=[
                ('planvariable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.planvariable')),
                ('value', models.TextField()),
            ],
            bases=('api.planvariable',),
        ),
        migrations.CreateModel(
            name='StrRateVariable',
            fields=[
                ('ratevariable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.ratevariable')),
                ('value', models.TextField()),
            ],
            bases=('api.ratevariable',),
        ),
        migrations.CreateModel(
            name='UnderwaterVolcanoCoveragePlanVariable',
            fields=[
                ('planvariable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.planvariable')),
                ('value', models.TextField()),
            ],
            bases=('api.planvariable',),
        ),
        migrations.AddField(
            model_name='plan',
            name='proximity_to_volcano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.proximitytovolcanoplanvariable'),
        ),
        migrations.AddField(
            model_name='plan',
            name='underwater_volcano_coverage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.underwatervolcanocoverageplanvariable'),
        ),
    ]
