# Generated by Django 3.1.4 on 2020-12-17 08:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line1', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('zip_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PlanVariable',
            fields=[
                ('variable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.variable')),
            ],
            bases=('api.variable',),
        ),
        migrations.CreateModel(
            name='RateVariable',
            fields=[
                ('variable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.variable')),
            ],
            bases=('api.variable',),
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quote_number', models.CharField(max_length=10)),
                ('effective_date', models.DateField()),
                ('previous_policy_cancelled', models.BooleanField(default=False)),
                ('property_mileage_to_nearest_volcano', models.FloatField()),
                ('owns_property_to_be_insured', models.BooleanField()),
                ('mailing_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailing_address', to='api.address')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='api.plan')),
                ('property_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_address', to='api.address')),
            ],
        ),
        migrations.CreateModel(
            name='ConvenienceFee',
            fields=[
                ('ratevariable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.ratevariable')),
                ('value', models.FloatField()),
            ],
            bases=('api.ratevariable',),
        ),
        migrations.CreateModel(
            name='CoverageLimit',
            fields=[
                ('planvariable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.planvariable')),
                ('value', models.FloatField()),
            ],
            bases=('api.planvariable',),
        ),
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('ratevariable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.ratevariable')),
                ('value', models.IntegerField()),
            ],
            bases=('api.ratevariable',),
        ),
        migrations.CreateModel(
            name='ProximityToVolcano',
            fields=[
                ('planvariable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.planvariable')),
                ('value', models.TextField()),
            ],
            bases=('api.planvariable',),
        ),
        migrations.CreateModel(
            name='SuperVolcanoCoverage',
            fields=[
                ('planvariable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.planvariable')),
                ('value', models.BooleanField()),
            ],
            bases=('api.planvariable',),
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('ratevariable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.ratevariable')),
                ('value', models.FloatField()),
            ],
            bases=('api.ratevariable',),
        ),
        migrations.CreateModel(
            name='UnderwaterVolcanoCoverage',
            fields=[
                ('planvariable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.planvariable')),
                ('value', models.BooleanField()),
            ],
            bases=('api.planvariable',),
        ),
        migrations.AddField(
            model_name='plan',
            name='convenience_fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.conveniencefee'),
        ),
        migrations.AddField(
            model_name='plan',
            name='coverage_limit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.coveragelimit'),
        ),
        migrations.AddField(
            model_name='plan',
            name='premium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.premium'),
        ),
        migrations.AddField(
            model_name='plan',
            name='proximity_to_volcano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.proximitytovolcano'),
        ),
        migrations.AddField(
            model_name='plan',
            name='super_volcano_coverage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.supervolcanocoverage'),
        ),
        migrations.AddField(
            model_name='plan',
            name='tax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tax'),
        ),
        migrations.AddField(
            model_name='plan',
            name='underwater_volcano_coverage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.underwatervolcanocoverage'),
        ),
    ]
