# Generated by Django 3.1.4 on 2020-12-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='is_owned',
            new_name='owns_property_to_be_insured',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='had_previous_policy_cancelled',
            new_name='previous_policy_cancelled',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='distance_to_volcano',
            new_name='property_mileage_to_nearest_volcano',
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quote',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
