# Generated by Django 3.1.4 on 2020-12-17 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratevariable',
            name='plans',
        ),
        migrations.AddField(
            model_name='planvariable',
            name='plans',
            field=models.ManyToManyField(related_name='plan_variables', to='api.Plan'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='proximity_to_volcano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_variables', to='api.proximitytovolcanoplanvariable'),
        ),
        migrations.AlterField(
            model_name='underwatervolcanocoverageplanvariable',
            name='value',
            field=models.BooleanField(),
        ),
    ]
