# Generated by Django 3.1.4 on 2020-12-17 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201217_0439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planvariable',
            name='plans',
        ),
    ]
