# Generated by Django 3.1.4 on 2020-12-15 19:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201215_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False),
        ),
    ]
