# Generated by Django 3.1.4 on 2020-12-17 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201217_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='plan',
            field=models.ForeignKey(default='4f788924d61f4d11ac6017f62f9e47b7', on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='api.plan'),
            preserve_default=False,
        ),
    ]
