# Generated by Django 3.1.4 on 2020-12-17 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_planvariable_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageLimitPlanVariable',
            fields=[
                ('planvariable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.planvariable')),
                ('value', models.FloatField()),
            ],
            bases=('api.planvariable',),
        ),
        migrations.CreateModel(
            name='SuperVolcanoCoveragePlanVariable',
            fields=[
                ('planvariable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.planvariable')),
                ('value', models.BooleanField()),
            ],
            bases=('api.planvariable',),
        ),
        migrations.AddField(
            model_name='plan',
            name='coverage_limit',
            field=models.ForeignKey(default='be99e7ceaf44402e8e37c04b08c86922', on_delete=django.db.models.deletion.CASCADE, to='api.coveragelimitplanvariable'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='super_volcano_coverage',
            field=models.ForeignKey(default='be99e7ceaf44402e8e37c04b08c86922', on_delete=django.db.models.deletion.CASCADE, to='api.supervolcanocoverageplanvariable'),
            preserve_default=False,
        ),
    ]
