# Generated by Django 3.1.4 on 2020-12-17 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201217_0523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boolratevariable',
            name='ratevariable_ptr',
        ),
        migrations.RemoveField(
            model_name='fltplanvariable',
            name='planvariable_ptr',
        ),
        migrations.RemoveField(
            model_name='fltratevariable',
            name='ratevariable_ptr',
        ),
        migrations.RemoveField(
            model_name='intplanvariable',
            name='planvariable_ptr',
        ),
        migrations.RemoveField(
            model_name='intratevariable',
            name='ratevariable_ptr',
        ),
        migrations.RemoveField(
            model_name='strratevariable',
            name='ratevariable_ptr',
        ),
        migrations.DeleteModel(
            name='BoolPlanVariable',
        ),
        migrations.DeleteModel(
            name='BoolRateVariable',
        ),
        migrations.DeleteModel(
            name='FltPlanVariable',
        ),
        migrations.DeleteModel(
            name='FltRateVariable',
        ),
        migrations.DeleteModel(
            name='IntPlanVariable',
        ),
        migrations.DeleteModel(
            name='IntRateVariable',
        ),
        migrations.DeleteModel(
            name='StrRateVariable',
        ),
    ]
