# Generated by Django 3.1.4 on 2020-12-15 19:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201215_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
