# Generated by Django 3.1.4 on 2020-12-17 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201217_0526'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvenienceFeeRateVariable',
            fields=[
                ('ratevariable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.ratevariable')),
                ('value', models.FloatField()),
            ],
            bases=('api.ratevariable',),
        ),
        migrations.CreateModel(
            name='PremiumRateVariable',
            fields=[
                ('ratevariable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.ratevariable')),
                ('value', models.IntegerField()),
            ],
            bases=('api.ratevariable',),
        ),
        migrations.CreateModel(
            name='TaxRateVariable',
            fields=[
                ('ratevariable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.ratevariable')),
                ('value', models.FloatField()),
            ],
            bases=('api.ratevariable',),
        ),
        migrations.AlterField(
            model_name='plan',
            name='proximity_to_volcano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.proximitytovolcanoplanvariable'),
        ),
        migrations.AddField(
            model_name='plan',
            name='convenience_fee',
            field=models.ForeignKey(default='be99e7ceaf44402e8e37c04b08c86922', on_delete=django.db.models.deletion.CASCADE, to='api.conveniencefeeratevariable'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='premium',
            field=models.ForeignKey(default='be99e7ceaf44402e8e37c04b08c86922', on_delete=django.db.models.deletion.CASCADE, to='api.premiumratevariable'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='tax',
            field=models.ForeignKey(default='be99e7ceaf44402e8e37c04b08c86922', on_delete=django.db.models.deletion.CASCADE, to='api.taxratevariable'),
            preserve_default=False,
        ),
    ]
