# Generated by Django 3.1.4 on 2020-12-17 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201217_0534'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConvenienceFeeRateVariable',
            new_name='ConvenienceFee',
        ),
        migrations.RenameModel(
            old_name='CoverageLimitPlanVariable',
            new_name='CoverageLimit',
        ),
        migrations.RenameModel(
            old_name='PremiumRateVariable',
            new_name='Premium',
        ),
        migrations.RenameModel(
            old_name='ProximityToVolcanoPlanVariable',
            new_name='ProximityToVolcano',
        ),
        migrations.RenameModel(
            old_name='SuperVolcanoCoveragePlanVariable',
            new_name='SuperVolcanoCoverage',
        ),
        migrations.RenameModel(
            old_name='TaxRateVariable',
            new_name='Tax',
        ),
        migrations.RenameModel(
            old_name='UnderwaterVolcanoCoveragePlanVariable',
            new_name='UnderwaterVolcanoCoverage',
        ),
    ]
